const { EmbedBuilder, AttachmentBuilder } = require('discord.js');
const { prisma, ensureUser, randomBetween, formatMoney, addTransaction, atomicTransfer } = require('../services/economy');
const { buildProfileCard } = require('../services/canvas');
const { EMOJI, COLORS, RARITY } = require('../ui/theme');

const ITEMS = [
  { name: 'قناع الظل', price: 150, type: 'protection', description: 'يزيد فرص الهروب', rarity: 'common' },
  { name: 'سيف نيون', price: 300, type: 'weapon', description: 'أداة للمغامرات', rarity: 'uncommon' },
  { name: 'خاتم الحظ', price: 700, type: 'luck', description: 'يزيد فرص النجاح', rarity: 'rare' },
  { name: 'درع أونيكس', price: 1200, type: 'shield', description: 'حماية من السرقة', rarity: 'epic' },
  { name: 'تاج أورون', price: 3000, type: 'vip', description: 'عنصر أسطوري نادر', rarity: 'legendary' }
];
const userOf = (message, id = message.author.id) => ensureUser(prisma, id, message.guildId, id === message.author.id ? message.author.username : (message.mentions.users.get(id)?.username || 'عضو'), id === message.author.id ? message.author.displayAvatarURL({ extension: 'png', size: 256 }) : null);
const money = (n) => formatMoney(n);

async function balance(message) {
  const user = await userOf(message); const rank = (await prisma.user.count({ where: { wallet: { gt: user.wallet } } })) + 1;
  const buffer = await buildProfileCard({ username: user.username, wallet: money(user.wallet), bank: money(user.bank), level: user.level, xp: user.xp, avatarUrl: user.avatarUrl, rank });
  return message.reply({ files: [new AttachmentBuilder(buffer, { name: 'auron-profile.png' })] });
}
async function bank(message) { const u = await userOf(message); return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.info).setTitle(`${EMOJI.bank} خزنة أورون`).setDescription(`${EMOJI.wallet} المحفظة: **${money(u.wallet)}**\n${EMOJI.bank} البنك: **${money(u.bank)}**`).setFooter({ text: 'Auron Banking System' })] }); }
async function daily(message) { const u = await userOf(message); const now = Date.now(); if (u.lastDaily && now - u.lastDaily.getTime() < 86400000) return message.reply(`${EMOJI.warning} المكافأة القادمة بعد **${Math.ceil((86400000 - (now - u.lastDaily.getTime())) / 3600000)} ساعة**.`); const reward = randomBetween(300, 900); const updated = await prisma.user.update({ where: { id: u.id }, data: { wallet: { increment: reward }, lastDaily: new Date() } }); await addTransaction(u.id, 'daily', reward, 'مكافأة يومية'); return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.gold).setTitle(`${EMOJI.daily} صندوق المكافأة اليومية`).setDescription(`حصلت على **${money(reward)}**\nرصيدك الآن **${money(updated.wallet)}**`).setFooter({ text: 'ارجع غدًا للمكافأة الكبرى!' })] }); }
async function work(message) { const u = await userOf(message); if (u.lastWork && Date.now() - u.lastWork.getTime() < 60000) return message.reply(`${EMOJI.warning} استرح قليلًا، حاول بعد دقيقة.`); const reward = randomBetween(100, 300); await prisma.user.update({ where: { id: u.id }, data: { wallet: { increment: reward }, xp: { increment: reward }, lastWork: new Date() } }); await addTransaction(u.id, 'work', reward, 'أجر العمل'); return message.reply(`${EMOJI.work} أنجزت مهمتك وربحت **${money(reward)}** ${EMOJI.xp}`); }
async function deposit(message, amount) { const n = Number(amount); const u = await userOf(message); if (!Number.isInteger(n) || n <= 0 || u.wallet < n) return message.reply(`${EMOJI.fail} مبلغ غير صالح أو رصيد المحفظة غير كافٍ.`); await prisma.$transaction([prisma.user.update({ where: { id: u.id }, data: { wallet: { decrement: n }, bank: { increment: n } } }), prisma.transaction.create({ data: { userId: u.id, type: 'deposit', amount: n, reason: 'إيداع' } })]); return message.reply(`${EMOJI.success} أودعت **${money(n)}** بأمان.`); }
async function withdraw(message, amount) { const n = Number(amount); const u = await userOf(message); if (!Number.isInteger(n) || n <= 0 || u.bank < n) return message.reply(`${EMOJI.fail} مبلغ غير صالح أو رصيد البنك غير كافٍ.`); await prisma.$transaction([prisma.user.update({ where: { id: u.id }, data: { wallet: { increment: n }, bank: { decrement: n } } }), prisma.transaction.create({ data: { userId: u.id, type: 'withdraw', amount: n, reason: 'سحب' } })]); return message.reply(`${EMOJI.success} سحبت **${money(n)}** من البنك.`); }
async function transfer(message, target, amount) { const n = Number(amount); if (!target || target.id === message.author.id || !Number.isInteger(n) || n <= 0) return message.reply(`${EMOJI.warning} الاستخدام: تحويل @عضو 250`); const from = await userOf(message); const to = await ensureUser(prisma, target.id, message.guildId, target.username, target.displayAvatarURL({ extension: 'png', size: 256 })); try { await atomicTransfer(from.id, to.id, n, `تحويل إلى ${target.username}`); return message.reply(`${EMOJI.transfer} تم تحويل **${money(n)}** إلى **${target.username}**.`); } catch { return message.reply(`${EMOJI.fail} لا تملك رصيدًا كافيًا.`); } }
async function shop(message) { await Promise.all(ITEMS.map((item) => prisma.shopItem.upsert({ where: { name: item.name }, update: item, create: item }))); const list = ITEMS.map((i) => `${RARITY[i.rarity].emoji} **${i.name}** — ${money(i.price)}\n> ${i.description}`).join('\n\n'); return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.primary).setTitle(`${EMOJI.shop} سوق أورون الأسطوري`).setDescription(list).setFooter({ text: 'للشراء: شراء اسم العنصر' })] }); }
async function buy(message, itemName) { const u = await userOf(message); const item = await prisma.shopItem.findFirst({ where: { name: { contains: String(itemName || '').trim(), mode: 'insensitive' }, enabled: true } }); if (!item) return message.reply(`${EMOJI.fail} العنصر غير موجود.`); if (u.wallet < item.price) return message.reply(`${EMOJI.lock} تحتاج إلى ${money(item.price - u.wallet)} إضافية.`); await prisma.$transaction(async (tx) => { await tx.user.update({ where: { id: u.id }, data: { wallet: { decrement: item.price } } }); const old = await tx.inventory.findFirst({ where: { userId: u.id, itemName: item.name } }); if (old) await tx.inventory.update({ where: { id: old.id }, data: { quantity: { increment: 1 } } }); else await tx.inventory.create({ data: { userId: u.id, itemName: item.name, quantity: 1 } }); await tx.transaction.create({ data: { userId: u.id, type: 'purchase', amount: item.price, reason: `شراء ${item.name}` } }); }); return message.reply(`${EMOJI.success} تم اقتناء **${item.name}** ${RARITY[item.rarity]?.emoji || ''}.`); }
async function inventory(message) { const u = await userOf(message); const rows = await prisma.inventory.findMany({ where: { userId: u.id }, orderBy: { itemName: 'asc' } }); return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.info).setTitle(`${EMOJI.item} حقيبتك`).setDescription(rows.length ? rows.map((r) => `• **${r.itemName}** × ${r.quantity}`).join('\n') : 'حقيبتك فارغة حاليًا.').setFooter({ text: 'اجمع العناصر النادرة لتصبح أسطورة!' })] }); }
async function rob(message, target) { const a = await userOf(message); if (!target || target.id === message.author.id) return message.reply(`${EMOJI.warning} الاستخدام: سرقة @عضو`); if (a.lastRob && Date.now() - a.lastRob.getTime() < 600000) return message.reply(`${EMOJI.warning} مهلة السرقة لم تنتهِ بعد.`); const v = await ensureUser(prisma, target.id, message.guildId, target.username); if (v.wallet < 150) return message.reply(`${EMOJI.fail} هدفك لا يحمل ما يكفي.`); const win = randomBetween(1, 100) <= 55; const amount = Math.min(randomBetween(60, 600), v.wallet); if (win) { await prisma.$transaction([prisma.user.update({ where: { id: a.id }, data: { wallet: { increment: amount }, lastRob: new Date() } }), prisma.user.update({ where: { id: v.id }, data: { wallet: { decrement: amount } } }), prisma.robberyLog.create({ data: { robberId: a.id, victimId: v.id, amount, success: true } })]); return message.reply(`${EMOJI.robbery} ${EMOJI.success} تمت العملية! غنيمتك **${money(amount)}**.`); } const fine = Math.min(randomBetween(30, 180), a.wallet); await prisma.user.update({ where: { id: a.id }, data: { wallet: { decrement: fine }, lastRob: new Date() } }); return message.reply(`${EMOJI.robbery} ${EMOJI.fail} انكشف أمرك وغرامتك **${money(fine)}**.`); }
async function crime(message) { const u = await userOf(message); const success = randomBetween(1, 100) <= 60; const amount = randomBetween(80, 350); if (success) { await prisma.user.update({ where: { id: u.id }, data: { wallet: { increment: amount } } }); return message.reply(`${EMOJI.crime} ${EMOJI.success} مهمة ناجحة: **${money(amount)}**.`); } const fine = Math.min(randomBetween(30, 150), u.wallet); await prisma.user.update({ where: { id: u.id }, data: { wallet: { decrement: fine }, jailUntil: new Date(Date.now() + 300000) } }); return message.reply(`${EMOJI.crime} ${EMOJI.fail} تم القبض عليك! غرامة **${money(fine)}** وسجن 5 دقائق ${EMOJI.jail}.`); }
async function leaderboard(message) { const users = await prisma.user.findMany({ orderBy: [{ wallet: 'desc' }, { bank: 'desc' }], take: 10 }); return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.gold).setTitle(`${EMOJI.crown} عرش الأثرياء`).setDescription(users.map((u, i) => `**${i + 1}.** ${u.username} — ${money(u.wallet + u.bank)}`).join('\n') || 'لا يوجد لاعبون بعد.')] }); }
async function company(message, value) { const u = await userOf(message); if (!value) return message.reply(`${EMOJI.company} الاستخدام: شركة إنشاء اسم_الشركة`); if (value.startsWith('إنشاء ')) { const name = value.slice(6).trim(); if (!name) return message.reply(`${EMOJI.warning} اكتب اسم الشركة.`); const exists = await prisma.company.findUnique({ where: { name } }); if (exists) return message.reply(`${EMOJI.fail} الاسم محجوز.`); const c = await prisma.company.create({ data: { name, ownerId: u.id } }); await prisma.companyMember.create({ data: { companyId: c.id, userId: u.id, role: 'owner' } }); return message.reply(`${EMOJI.company} ${EMOJI.success} تأسست شركة **${name}**.`); } const c = await prisma.company.findFirst({ where: { OR: [{ ownerId: u.id }, { members: { some: { userId: u.id } } }] }, include: { members: true } }); return message.reply(c ? `${EMOJI.company} **${c.name}**\n👥 الموظفون: ${c.members.length}\n💼 الخزنة: ${money(c.balance)}` : `${EMOJI.fail} أنت لست في شركة.`); }
async function help(message) { return message.reply({ embeds: [new EmbedBuilder().setColor(COLORS.primary).setTitle(`${EMOJI.help} دليل أورون`).setDescription('**💰 الاقتصاد:** حساب، بنك، يومية، عمل، إيداع، سحب، تحويل\n**🛍️ العناصر:** متجر، شراء، مخزون\n**🎭 المغامرة:** سرقة، جريمة، قمار\n**🏢 المجتمع:** شركة، قائمة\n\nكل الأوامر تعمل بدون بادئة.') ] }); }
module.exports = { balance, bank, daily, work, deposit, withdraw, transfer, shop, buy, inventory, rob, crime, leaderboard, company, help };
