const { Client, GatewayIntentBits, PermissionFlagsBits, SlashCommandBuilder } = require('discord.js');
const { token } = require('./config');
const { prisma, ensureUser, formatMoney, addTransaction } = require('./services/economy');
const game = require('./commands/game');

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });
const commands = {
  حساب: game.balance, رصيد: game.balance, بنك: game.bank, يومية: game.daily, عمل: game.work,
  متجر: game.shop, شراء: (m, r) => game.buy(m, r), مخزون: game.inventory, سرقة: (m) => game.rob(m, m.mentions.users.first()),
  جريمة: game.crime, قائمة: game.leaderboard, شركة: (m, r) => game.company(m, r), مساعدة: game.help,
  إيداع: (m, r) => game.deposit(m, r), سحب: (m, r) => game.withdraw(m, r),
  تحويل: (m, r) => game.transfer(m, m.mentions.users.first(), String(r).replace(/<@!?\d+>/, '').trim())
};
const adminCommands = [
  new SlashCommandBuilder().setName('اعطاء').setDescription('إضافة أموال').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o => o.setName('مستخدم').setDescription('العضو').setRequired(true)).addIntegerOption(o => o.setName('مبلغ').setDescription('المبلغ').setRequired(true).setMinValue(1)),
  new SlashCommandBuilder().setName('سحب').setDescription('خصم أموال').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o => o.setName('مستخدم').setDescription('العضو').setRequired(true)).addIntegerOption(o => o.setName('مبلغ').setDescription('المبلغ').setRequired(true).setMinValue(1)),
  new SlashCommandBuilder().setName('تجميد').setDescription('سجن عضو').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o => o.setName('مستخدم').setDescription('العضو').setRequired(true)).addIntegerOption(o => o.setName('دقائق').setDescription('المدة').setRequired(true).setMinValue(1)),
  new SlashCommandBuilder().setName('اضافة_عنصر').setDescription('إضافة عنصر').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o => o.setName('اسم').setDescription('الاسم').setRequired(true)).addIntegerOption(o => o.setName('سعر').setDescription('السعر').setRequired(true).setMinValue(1)).addStringOption(o => o.setName('نوع').setDescription('النوع').setRequired(true)).addStringOption(o => o.setName('وصف').setDescription('الوصف').setRequired(true)),
  new SlashCommandBuilder().setName('تسجيلات').setDescription('عرض السجل').setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
];
async function admin(interaction) { if (!interaction.memberPermissions?.has(PermissionFlagsBits.Administrator)) return interaction.reply({ content: '❌ هذا الأمر للإدارة فقط.', ephemeral: true }); const name = interaction.commandName; if (name === 'تسجيلات') { const rows = await prisma.adminLog.findMany({ where: { guildId: interaction.guildId }, orderBy: { createdAt: 'desc' }, take: 15 }); return interaction.reply({ content: rows.map(r => `${r.action} — ${r.reason || ''}`).join('\n') || 'لا يوجد سجل.' }); } const target = interaction.options.getUser('مستخدم'); const u = await ensureUser(target.id, interaction.guildId, target.username); if (name === 'اعطاء' || name === 'سحب') { const amount = interaction.options.getInteger('مبلغ'); const delta = name === 'اعطاء' ? amount : -amount; await prisma.user.update({ where: { id: u.id }, data: { wallet: { increment: delta } } }); await addTransaction(u.id, `admin_${name}`, amount, 'إجراء إداري'); await prisma.adminLog.create({ data: { guildId: interaction.guildId, adminId: interaction.user.id, action: name, targetId: target.id } }); return interaction.reply(`${name === 'اعطاء' ? '✅' : '🧾'} تم تحديث رصيد ${target.username} بمقدار ${formatMoney(amount)}.`); } const minutes = interaction.options.getInteger('دقائق'); await prisma.user.update({ where: { id: u.id }, data: { jailUntil: new Date(Date.now() + minutes * 60000) } }); await prisma.adminLog.create({ data: { guildId: interaction.guildId, adminId: interaction.user.id, action: 'تجميد', targetId: target.id } }); return interaction.reply(`🚓 تم سجن ${target.username} لمدة ${minutes} دقيقة.`); }
client.once('ready', async () => { await client.application.commands.set(adminCommands.map(c => c.toJSON())); console.log(`✅ Auron V3 online as ${client.user.tag}`); });
client.on('messageCreate', async message => { if (message.author.bot || !message.guild) return; const [name, ...rest] = message.content.trim().split(/\s+/); const handler = commands[name]; if (!handler) return; try { await handler(message, rest.join(' ')); } catch (error) { console.error(error); await message.reply('❌ حدث خطأ غير متوقع، حاول مرة أخرى.'); } });
client.on('interactionCreate', async interaction => { if (interaction.isChatInputCommand()) { try { await admin(interaction); } catch (error) { console.error(error); const reply = { content: '❌ تعذر تنفيذ الأمر.', ephemeral: true }; if (interaction.replied || interaction.deferred) await interaction.followUp(reply); else await interaction.reply(reply); } } });
client.login(token);
